const snacks = [
  {
    id: 1,
    name: "Classic Veg Burger",
    category: "BURGERS",
    ingredients: [
      "1 veggie patty",
      "1 burger bun",
      "Lettuce leaves",
      "Tomato slices",
      "Onion rings",
      "Mayonnaise",
      "Ketchup",
      "Cheese slice",
    ],
    img: "classic_veg_burger.jpg",
    directions: [
      "Cook the veggie patty according to package instructions.",
      "Cut the burger bun in half and toast it lightly.",
      "Spread mayonnaise and ketchup on the toasted buns.",
      "Place lettuce leaves, tomato slices, and onion rings on the bottom bun.",
      "Put the cooked veggie patty on top of the veggies.",
      "Add a cheese slice on top of the patty.",
      "Cover with the top bun and serve.",
    ],
  },
  {
    id: 2,
    name: "Spicy Chickpea Burger",
    category: "BURGERS",
    ingredients: [
      "1 can chickpeas, drained and mashed",
      "1/2 cup breadcrumbs",
      "1/4 cup chopped red bell pepper",
      "1/4 cup chopped red onion",
      "1 clove garlic, minced",
      "1 tsp cumin powder",
      "1/2 tsp paprika",
      "Salt and pepper to taste",
      "4 burger buns",
      "Lettuce leaves",
      "Sliced cucumber",
      "Tahini sauce",
    ],
    img: "spicy_chickpea_burger.jpg",
    directions: [
      "In a bowl, combine mashed chickpeas, breadcrumbs, bell pepper, red onion, garlic, cumin powder, paprika, salt, and pepper.",
      "Form the mixture into burger patties and refrigerate for 30 minutes.",
      "Grill the chickpea patties until they are heated through and have grill marks.",
      "Cut the burger buns in half and toast them.",
      "Spread tahini sauce on the bottom bun.",
      "Place lettuce leaves, sliced cucumber, and a chickpea patty on top of the sauce.",
      "Cover with the top bun and serve.",
    ],
  },
  {
    id: 3,
    name: "Mushroom Swiss Burger",
    category: "BURGERS",
    ingredients: [
      "2 portobello mushrooms, stems removed",
      "2 burger buns",
      "Swiss cheese slices",
      "Caramelized onions",
      "Mayonnaise",
      "Dijon mustard",
      "Lettuce leaves",
      "Tomato slices",
    ],
    img: "mushroom_swiss_burger.jpg",
    directions: [
      "Brush portobello mushrooms with olive oil and grill until tender.",
      "Cut the burger buns in half and toast them.",
      "Spread mayonnaise and Dijon mustard on the toasted buns.",
      "Place lettuce leaves and tomato slices on the bottom bun.",
      "Put a grilled portobello mushroom on top of the veggies.",
      "Add Swiss cheese and caramelized onions.",
      "Cover with the top bun and serve.",
    ],
  },
  {
    id: 4,
    name: "Spicy Bean Burger",
    category: "BURGERS",
    ingredients: [
      "1 can black beans, drained and mashed",
      "1/2 cup breadcrumbs",
      "1/4 cup diced red onion",
      "1/4 cup diced bell pepper",
      "1/4 cup corn kernels",
      "1/2 tsp chili powder",
      "1/2 tsp cumin powder",
      "Salt and pepper to taste",
      "4 burger buns",
      "Salsa",
      "Lettuce leaves",
      "Sliced avocado",
    ],
    img: "spicy_bean_burger.jpg",
    directions: [
      "In a bowl, combine mashed black beans, breadcrumbs, red onion, bell pepper, corn, chili powder, cumin powder, salt, and pepper.",
      "Form the mixture into burger patties and refrigerate for 30 minutes.",
      "Grill the bean patties until they are heated through and have grill marks.",
      "Cut the burger buns in half and toast them.",
      "Spread salsa on the bottom bun.",
      "Place lettuce leaves, a bean patty, and sliced avocado on top of the salsa.",
      "Cover with the top bun and serve.",
    ],
  },
  {
    id: 5,
    name: "Veggie Deluxe Burger",
    category: "BURGERS",
    ingredients: [
      "1 veggie patty",
      "1 burger bun",
      "Lettuce leaves",
      "Tomato slices",
      "Red onion slices",
      "Pickles",
      "Ketchup",
      "Mustard",
      "Vegan cheese slice",
    ],
    img: "veggie_deluxe_burger.jpg",
    directions: [
      "Cook the veggie patty according to package instructions.",
      "Cut the burger bun in half and toast it lightly.",
      "Spread ketchup and mustard on the toasted buns.",
      "Place lettuce leaves, tomato slices, red onion slices, and pickles on the bottom bun.",
      "Put the cooked veggie patty on top of the veggies.",
      "Add a vegan cheese slice on top of the patty.",
      "Cover with the top bun and serve.",
    ],
  },
  {
    id: 6,
    name: "Avocado and Bean Burger",
    category: "BURGERS",
    ingredients: [
      "1 can black beans, drained and mashed",
      "1/2 cup breadcrumbs",
      "1 ripe avocado, mashed",
      "1/4 cup diced red onion",
      "1/4 cup diced bell pepper",
      "1/2 tsp cumin powder",
      "1/2 tsp paprika",
      "Salt and pepper to taste",
      "4 burger buns",
      "Lettuce leaves",
      "Sliced tomato",
    ],
    img: "avocado_bean_burger.jpg",
    directions: [
      "In a bowl, combine mashed black beans, breadcrumbs, mashed avocado, red onion, bell pepper, cumin powder, paprika, salt, and pepper.",
      "Form the mixture into burger patties and refrigerate for 30 minutes.",
      "Grill the bean and avocado patties until they are heated through and have grill marks.",
      "Cut the burger buns in half and toast them.",
      "Place lettuce leaves and sliced tomato on the bottom bun.",
      "Put a grilled bean and avocado patty on top of the veggies.",
      "Cover with the top bun and serve.",
    ],
  },
  {
    id: 7,
    name: "Vegan BBQ Burger",
    category: "BURGERS",
    ingredients: [
      "1 vegan burger patty",
      "1 burger bun",
      "BBQ sauce",
      "Grilled pineapple slice",
      "Vegan cheese slice",
      "Lettuce leaves",
      "Red onion rings",
    ],
    img: "vegan_bbq_burger.jpg",
    directions: [
      "Cook the vegan burger patty according to package instructions.",
      "Cut the burger bun in half and toast it lightly.",
      "Spread BBQ sauce on the toasted buns.",
      "Place lettuce leaves, a grilled pineapple slice, a vegan cheese slice, and red onion rings on the bottom bun.",
      "Put the cooked vegan burger patty on top of the veggies.",
      "Cover with the top bun and serve.",
    ],
  },
  {
    id: 8,
    name: "Margherita Pizza",
    category: "PIZZA",
    ingredients: [
      "Pizza dough",
      "Tomato sauce",
      "Fresh mozzarella cheese",
      "Fresh basil leaves",
      "Olive oil",
      "Salt and pepper to taste",
    ],
    img: "margherita_pizza.jpg",
    directions: [
      "Preheat your oven to the highest temperature (usually 500°F or 260°C).",
      "Roll out the pizza dough into a circle on a floured surface.",
      "Spread tomato sauce evenly over the dough.",
      "Add slices of fresh mozzarella cheese on top of the sauce.",
      "Sprinkle with salt and pepper to taste.",
      "Bake in the preheated oven until the crust is golden and the cheese is bubbly and slightly browned.",
      "Remove from the oven, top with fresh basil leaves, and drizzle with olive oil.",
      "Slice and serve hot.",
    ],
  },
  {
    id: 9,
    name: "Vegetable Supreme Pizza",
    category: "PIZZA",
    ingredients: [
      "Pizza dough",
      "Tomato sauce",
      "Shredded mozzarella cheese",
      "Sliced bell peppers",
      "Sliced red onion",
      "Sliced black olives",
      "Sliced mushrooms",
      "Sliced tomatoes",
      "Oregano and basil for seasoning",
      "Olive oil",
      "Salt and pepper to taste",
    ],
    img: "vegetable_supreme_pizza.jpg",
    directions: [
      "Preheat your oven to the highest temperature (usually 500°F or 260°C).",
      "Roll out the pizza dough into a circle on a floured surface.",
      "Spread tomato sauce evenly over the dough.",
      "Sprinkle shredded mozzarella cheese over the sauce.",
      "Add sliced bell peppers, red onion, black olives, mushrooms, and tomatoes as desired.",
      "Season with oregano, basil, salt, and pepper.",
      "Drizzle olive oil over the pizza.",
      "Bake until the crust is golden and the cheese is bubbly and slightly browned.",
      "Slice and serve.",
    ],
  },
  {
    id: 10,
    name: "Spinach and Feta Pizza",
    category: "PIZZA",
    ingredients: [
      "Pizza dough",
      "Tomato sauce",
      "Crumbled feta cheese",
      "Fresh spinach leaves",
      "Sliced red onion",
      "Sliced black olives",
      "Minced garlic",
      "Olive oil",
      "Salt and pepper to taste",
    ],
    img: "spinach_feta_pizza.jpg",
    directions: [
      "Preheat your oven to the highest temperature (usually 500°F or 260°C).",
      "Roll out the pizza dough into a circle on a floured surface.",
      "Spread tomato sauce evenly over the dough.",
      "Sprinkle crumbled feta cheese over the sauce.",
      "Add fresh spinach leaves, sliced red onion, and black olives.",
      "Sprinkle minced garlic, salt, and pepper.",
      "Drizzle olive oil over the pizza.",
      "Bake until the crust is golden and the cheese is bubbly and slightly browned.",
      "Slice and serve.",
    ],
  },
  {
    id: 11,
    name: "BBQ Veggie Pizza",
    category: "PIZZA",
    ingredients: [
      "Pizza dough",
      "BBQ sauce",
      "Shredded mozzarella cheese",
      "Sliced bell peppers",
      "Sliced red onion",
      "Sliced zucchini",
      "Corn kernels",
      "Chopped cilantro",
      "Olive oil",
      "Salt and pepper to taste",
    ],
    img: "bbq_veggie_pizza.jpg",
    directions: [
      "Preheat your oven to the highest temperature (usually 500°F or 260°C).",
      "Roll out the pizza dough into a circle on a floured surface.",
      "Spread BBQ sauce evenly over the dough.",
      "Sprinkle shredded mozzarella cheese over the sauce.",
      "Add sliced bell peppers, red onion, zucchini, and corn kernels.",
      "Season with salt and pepper.",
      "Drizzle olive oil over the pizza.",
      "Bake until the crust is golden and the cheese is bubbly and slightly browned.",
      "Top with chopped cilantro, slice, and serve.",
    ],
  },
  {
    id: 12,
    name: "Pesto and Tomato Pizza",
    category: "PIZZA",
    ingredients: [
      "Pizza dough",
      "Pesto sauce",
      "Cherry tomatoes, halved",
      "Fresh mozzarella cheese",
      "Fresh basil leaves",
      "Olive oil",
      "Balsamic glaze (optional)",
      "Salt and pepper to taste",
    ],
    img: "pesto_tomato_pizza.jpg",
    directions: [
      "Preheat your oven to the highest temperature (usually 500°F or 260°C).",
      "Roll out the pizza dough into a circle on a floured surface.",
      "Spread pesto sauce evenly over the dough.",
      "Add halved cherry tomatoes and fresh mozzarella cheese on top of the sauce.",
      "Sprinkle with salt and pepper to taste.",
      "Bake in the preheated oven until the crust is golden and the cheese is bubbly and slightly browned.",
      "Remove from the oven, top with fresh basil leaves, drizzle with olive oil, and optionally add balsamic glaze.",
      "Slice and serve hot.",
    ],
  },
  {
    id: 14,
    name: "Chocolate Cake",
    category: "DESSERT",
    ingredients: [
      "2 cups all-purpose flour",
      "1 3/4 cups granulated sugar",
      "3/4 cup unsweetened cocoa powder",
      "1 1/2 tsp baking powder",
      "1 1/2 tsp baking soda",
      "1 tsp salt",
      "2 eggs",
      "1 cup milk",
      "1/2 cup vegetable oil",
      "2 tsp vanilla extract",
      "1 cup boiling water",
      "1 cup semisweet chocolate chips",
      "1/2 cup powdered sugar (for dusting)",
    ],
    img: "chocolate_cake.jpg",
    directions: [
      "Preheat your oven to 350°F (175°C). Grease and flour two 9-inch round cake pans.",
      "In a large bowl, whisk together flour, granulated sugar, cocoa powder, baking powder, baking soda, and salt.",
      "Add eggs, milk, vegetable oil, and vanilla extract. Beat on medium speed for 2 minutes.",
      "Stir in boiling water until the batter is smooth. The batter will be thin; that's okay.",
      "Fold in chocolate chips.",
      "Pour the batter evenly into the prepared pans.",
      "Bake for 30 to 35 minutes in the preheated oven, until a toothpick inserted into the center comes out clean.",
      "Allow the cakes to cool in the pans for 10 minutes, then remove from the pans and let cool completely on a wire rack.",
      "Once cooled, dust with powdered sugar, slice, and serve.",
    ],
  },
  {
    id: 15,
    name: "Strawberry Shortcake",
    category: "DESSERT",
    ingredients: [
      "1 1/2 cups all-purpose flour",
      "1/3 cup granulated sugar",
      "1 1/2 tsp baking powder",
      "1/4 tsp baking soda",
      "1/4 tsp salt",
      "1/2 cup unsalted butter, cold and cubed",
      "1/2 cup buttermilk",
      "1 tsp vanilla extract",
      "2 cups fresh strawberries, sliced",
      "1 cup heavy cream",
      "2 tbsp powdered sugar",
    ],
    img: "strawberry_shortcake.jpg",
    directions: [
      "Preheat your oven to 425°F (220°C).",
      "In a large bowl, whisk together flour, granulated sugar, baking powder, baking soda, and salt.",
      "Add cold, cubed butter and use a pastry cutter or fork to cut the butter into the dry ingredients until it resembles coarse crumbs.",
      "Stir in buttermilk and vanilla extract until the dough comes together.",
      "Turn the dough out onto a floured surface and knead it gently a few times until it holds together.",
      "Pat the dough into a 3/4-inch thick circle and use a round biscuit cutter to cut out shortcakes.",
      "Place the shortcakes on a baking sheet and bake for 12-15 minutes or until they are golden brown.",
      "While the shortcakes cool, whisk together heavy cream and powdered sugar until soft peaks form.",
      "Slice the shortcakes in half, top with sliced strawberries, and whipped cream. Place the other half of the shortcake on top, and serve.",
    ],
  },
  {
    id: 16,
    name: "Banana Bread",
    category: "DESSERT",
    ingredients: [
      "2 to 3 ripe bananas, mashed",
      "1/3 cup melted butter",
      "1 cup granulated sugar",
      "1 egg, beaten",
      "1 tsp vanilla extract",
      "1 tsp baking soda",
      "Pinch of salt",
      "1 1/2 cups all-purpose flour",
    ],
    img: "banana_bread.jpg",
    directions: [
      "Preheat your oven to 350°F (175°C). Grease a 4x8 inch loaf pan.",
      "In a mixing bowl, mash the ripe bananas with a fork until smooth.",
      "Stir the melted butter into the mashed bananas.",
      "Mix in the baking soda and pinch of salt.",
      "Add the sugar, beaten egg, and vanilla extract, and mix well.",
      "Stir in the flour until just incorporated.",
      "Pour the batter into the greased loaf pan.",
      "Bake in the preheated oven for about 60 minutes or until a toothpick inserted into the center comes out clean.",
      "Let the banana bread cool in the pan for a few minutes, then transfer to a wire rack to cool completely before slicing and serving.",
    ],
  },
  {
    id: 17,
    name: "Chocolate Chip Cookies",
    category: "DESSERT",
    ingredients: [
      "2 1/4 cups all-purpose flour",
      "1/2 tsp baking soda",
      "1 cup unsalted butter, room temperature",
      "1/2 cup granulated sugar",
      "1 cup packed light-brown sugar",
      "1 tsp salt",
      "2 tsp pure vanilla extract",
      "2 large eggs",
      "2 cups semisweet and/or milk chocolate chips",
    ],
    img: "chocolate_chip_cookies.jpg",
    directions: [
      "Preheat your oven to 350°F (175°C).",
      "In a small bowl, whisk together the flour and baking soda; set aside.",
      "In the bowl of an electric mixer, combine the butter with both granulated sugar and light-brown sugar; beat on medium speed until light and fluffy.",
      "Reduce speed to low; add the salt, vanilla, and eggs. Beat until well mixed, about 1 minute.",
      "Add flour mixture; mix until just combined.",
      "Stir in the chocolate chips.",
      "Drop heaping tablespoon-size balls of dough about 2 inches apart on baking sheets lined with parchment paper.",
      "Bake until cookies are golden around the edges, but still soft in the center, 8 to 10 minutes.",
      "Remove from oven, and let cool on baking sheet 1 to 2 minutes.",
      "Transfer to a wire rack, and let cool completely.",
    ],
  },
  {
    id: 18,
    name: "Vanilla Panna Cotta with Berry Sauce",
    category: "DESSERT",
    ingredients: [
      "2 cups heavy cream",
      "1/2 cup granulated sugar",
      "1 vanilla bean, split lengthwise, seeds scraped out",
      "2 1/2 tsp unflavored gelatin",
      "3 tbsp cold water",
      "Mixed berries (strawberries, blueberries, raspberries) for sauce",
      "1/4 cup powdered sugar for sauce",
    ],
    img: "vanilla_panna_cotta.jpg",
    directions: [
      "In a saucepan, combine heavy cream, granulated sugar, and vanilla bean seeds. Heat over medium heat until it begins to steam but not boil. Remove from heat.",
      "In a small bowl, sprinkle the gelatin over the cold water and let it sit for about 5 minutes to bloom.",
      "Remove the vanilla bean from the cream mixture. Reheat the cream over low heat until warm.",
      "Add the gelatin mixture to the warm cream and stir until the gelatin is completely dissolved.",
      "Pour the mixture into serving glasses or molds. Refrigerate for at least 4 hours or until set.",
      "In a blender, combine mixed berries and powdered sugar. Blend until smooth.",
      "Before serving, top each panna cotta with berry sauce. You can also garnish with fresh berries if desired.",
    ],
  },
];

export default snacks;
